name: 액션 연습

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 간단한 출력
        run: echo "안녕"

      - name: 다중 명령어 실행
        run: |
          echo "2025"
          echo "2월"
          echo "25일"

      - name: github 내장 변수
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
