name: 액션 연습

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key : ${{ secrets.EC2_KEY }}}}
          script_stop : true
          script:
            cd ~
            echo "test" > ./test.log


      