name: github auto-puller

on: 
  push:
    branches:
      - main  # main 브랜치에 push될 때
      - dev   # dev 브랜치에 push될 때
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 코드 체크아웃

    - name: Set up SSH key for main server
      if: github.ref == 'refs/heads/main'  # main 브랜치에 push된 경우
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_MAIN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_MAIN }} >> ~/.ssh/known_hosts  # 서버 호스트 확인

    - name: Executing remote SSH commands for main server
      if: github.ref == 'refs/heads/main'  # main 브랜치에 push된 경우
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_MAIN }}  # main 서버의 호스트
        username: ${{ secrets.USERNAME_MAIN }}  # 사용자명
        private-key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}  # PEM 형식의 SSH 비공개 키 사용
        port: ${{ secrets.PORT_MAIN }}  # 포트
        script: |
          bash ~/aws/start.sh  # main 서버에서 실행할 스크립트

    - name: Executing remote SSH commands for dev branch
      if: github.ref == 'refs/heads/dev'  # dev 브랜치에 push된 경우
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_DEV }}  # dev 서버의 호스트
        username: ${{ secrets.USERNAME_DEV }}  # 사용자명
        password: ${{ secrets.PASSWORD_DEV }}  # 비밀번호
        port: ${{ secrets.PORT_DEV }}  # 포트
        script: |
          bash ~/aws/start.sh  # dev 서버에서 실행할 스크립트
